services:
  api:
    image: node:22.14.0
    container_name: chat-system-container
    working_dir: /usr/chat-system
    restart: always
    ports:
      - 3000:3000
      - 9222:9222
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./dist/:/usr/chat-system/dist/
      - ./src/:/usr/chat-system/src/
      - ./package.json:/usr/chat-system/package.json
      - ./tsconfig.json:/usr/chat-system/tsconfig.json
      - ./tsconfig.paths.json:/usr/chat-system/tsconfig.paths.json
    depends_on:
      - dynamodb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "4566:8000"
    networks:
      - default

networks:
  default:
    driver: bridge